import { TrainCategory } from "./Train.types";

/**
 * The categories of trains that are archived.
 */
export type ArchivalTrainCategory = Extract<TrainCategory, "Commuter" | "Long-distance">;

/**
 * The shape of the JSON that's generated by
 * the parser, and stored in the archive bucket.
 */
export interface IArchiveEntry {
  date: string;
  trips: ITrip[];
}

export interface ITrip {
  /**
   * Origin and destination station ids.
   */
  id: string;
  /**
   * Train category.
   */
  cat: ArchivalTrainCategory;
  /**
   * Train line id.
   */
  tid: string;
  /**
   * Train type.
   */
  typ: string;
  stops: ITripStop[];
}

export interface ITripStop {
  /**
   * Station id.
   */
  id: string;
  /**
   * Timestamp of arrival.
   */
  t?: number;
  /**
   * Delta between timetable and actual arrival time.
   */
  d?: number;
  /**
   * Set if this leg has been cancelled.
   */
  cancelled?: true;
  /**
   * Delay cause ids can be mapped to
   * human-readable descriptions.
   */
  causes?: number[];
}
